title: The Bonfire Processor
description:
google_analytics:
show_downloads: false
#theme: jekyll-theme-dinky
remote_theme:  mmistakes/jekyll-theme-basically-basic

exclude: [ archive ]

lang: en-US

github_username: bonfireprocessor
email: info@bonfirecpu.eu
gitter_channel: bonfirecpu/community

name: The Bonfire Processor Project 

plugins:
  - jekyll-mentions
  - jekyll-remote-theme
